### ISSUE TITLE
{loc} lacking

### ISSUE THREAD

**Issue by MrReacher** [Snazzah/SublimeDiscordRP#33]
As you committed 22 days ago, it says you've added {loc} for displaying the number of lines.
I have installed the Discord Rich Presence plugin using the Package Control, I've tried changing the settings to fit my preferences and passed {loc} into one of the fields.

This is the full traceback:
```Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 577, in on_modified_async
    callback.on_modified_async(v)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\Discord Rich Presence.sublime-package\drp.py", line 258, in on_modified_async
    handle_activity(view)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\Discord Rich Presence.sublime-package\drp.py", line 130, in handle_activity
    act['state'] = state_format.format(**format_dict)
KeyError: 'loc'
```

Do I have to install the updated version from the github itself, or am I doing something wrong?

**Comment by FichteFoll** [comment]
Yeah, I haven't pushed a release since I merged it. You can see that by opening the commit (https://github.com/Snazzah/SublimeDiscordRP/commit/0335b9c4b76731756d5895e5c9ab9a45279cff95) in your browser and noticing that there are no tags listed besides `master` below the commit message.

I'll try to remember it when I'm back home next week, or @Snazzah can do it.

**Comment by MrReacher** [comment]
@FichteFoll, any news?
