### ISSUE TITLE
Not work when Discord has update available

### ISSUE THREAD

**Issue by Tansc161** [Snazzah/SublimeDiscordRP#35]
Since Discord update frequently these days, I've encountered this issue for almost everyday.
When Discord has update, it will not work even I try to reconnecting several times.
It only works after I quit Discord and run it again to install its update.
Traceback log:
```
reloading plugin xxx × n
plugins loaded
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\Discord Rich Presence.sublime-package\drp.py", line 208, in connect
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\Discord Rich Presence.sublime-package\discord_ipc/__init__.py", line 51, in for_platform
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\Discord Rich Presence.sublime-package\discord_ipc/__init__.py", line 44, in __init__
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\Discord Rich Presence.sublime-package\discord_ipc/__init__.py", line 170, in _connect
Discord Rich Presence.discord_ipc.DiscordIpcError: Failed to connect to Discord pipe
Package Control: No updated packages
```

Is it possible to fix this issue?

**Comment by Tansc161** [comment]
Nothing is shown if I didn't update Discord, happens today too.

After I installed those updates, it shows these messages when I try to reconnect (working normally)
![Discord IPC message](https://user-images.githubusercontent.com/37703689/48661884-4a845700-eab4-11e8-9605-6f9b21f2689a.png)

**Comment by FichteFoll** [comment]
Does this still happen?

**Comment by Tansc161** [comment]
Nope recently.

**Comment by Shogun05** [comment]
Can you tell me what you did to fix it? I seem to be facing the same issue...
