### ISSUE TITLE
Stopped working for me

### ISSUE THREAD

**Issue by notasgoodasyou** [Snazzah/SublimeDiscordRP#41]
I am on Sublime build 3207 and can't get the package to work. It used to work fine and suddenly stopped working. Here is the console log:

```
Traceback (most recent call last):
  File "/Users/macbook/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/drp.py", line 277, in run_async
  File "/Users/macbook/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/drp.py", line 213, in connect
  File "/Users/macbook/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 53, in for_platform
  File "/Users/macbook/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 44, in __init__
  File "/Users/macbook/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 191, in _connect
  File "/Users/macbook/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 212, in _iter_path_candidates
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by FichteFoll** [comment]
Thanks for the report.

**Comment by notasgoodasyou** [comment]
Is this fixed? I have the latest release 2.1.8 and it is still giving me this error.

**Comment by FichteFoll** [comment]
The commit should make that exception impossible to occur. Are you sure you are getting the exact same exception?

**Comment by notasgoodasyou** [comment]
It seems to be working now, not sure what happened there. Thanks!
