### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by dmilith** [Snazzah/SublimeDiscordRP#63]
Just installed it via package installer, I'm on macOS 11.1, x86_64

Console log:

```[Discord Rich Presence.drp] ERROR: Sending activity failed. Error: [Errno 32] Broken pipe
ERROR:Discord Rich Presence.drp:Sending activity failed. Error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 892, in on_close
    callback(v)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Installed Packages/Discord Rich Presence.sublime-package/drp.py", line 333, in on_close
    try: ipc.set_activity(act)
AttributeError: 'NoneType' object has no attribute 'set_activity'
[Discord Rich Presence.discord_ipc] WARNING: closing connection
WARNING:Discord Rich Presence.discord_ipc:closing connection
```

**Comment by dmilith** [comment]
Ok, it's solvable via http://s.verknowsys.com/5d3d386022c3386f81533a4e80a49a3b.png option. Discord.app has to have this enabled, which is not mentioned in readme? :)
