### ISSUE TITLE
Support Discord from Flatpak

### ISSUE THREAD

**Issue by genericusername3** [Snazzah/SublimeDiscordRP#80]
## Is there plans to add support for Discord's Flatpak package (from Flathub)?
---
### How I got here

Sublime Console said this:
```
[Discord Rich Presence.drp] INFO: Trying to reconnect to Discord client...
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-0' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-1' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-2' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-3' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-4' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-5' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-6' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-7' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-8' not found
[Discord Rich Presence.discord_ipc] DEBUG: '/run/user/1000/discord-ipc-9' not found
[Discord Rich Presence.drp] INFO: Unable to connect to Discord client
[Discord Rich Presence.drp] DEBUG: Error while connecting
Traceback (most recent call last):
  File "/home/<username>/.config/sublime-text/Installed Packages/Discord Rich Presence.sublime-package/drp.py", line 280, in connect
    ipc = discord_ipc.DiscordIpcClient.for_platform(DISCORD_CLIENT_ID)
  File "/home/<username>/.config/sublime-text/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 53, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/<username>/.config/sublime-text/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 44, in __init__
    self._connect()
  File "/home/<username>/.config/sublime-text/Installed Packages/Discord Rich Presence.sublime-package/discord_ipc/__init__.py", line 205, in _connect
    raise DiscordIpcError("Failed to connect to a Discord pipe")
Discord Rich Presence.discord_ipc.DiscordIpcError: Failed to connect to a Discord pipe
```

I've checked `/run/user/1000` and `/run/user/1000/discord-ipc-<0-9>` doesn't exist, but `/run/user/1000/app/com.discordapp.Discord/discord-ipc-0` does. "`com.discordapp.Discord`" seemed to be something Flatpak does, so I tried the same with the package from the pacman `community` repo, which worked perfectly.

**Comment by genericusername3** [comment]
Related to  #36 and #38

**Comment by Snazzah** [comment]
It does seem that @FichteFoll made a commit to fix this this issue (https://github.com/Snazzah/SublimeDiscordRP/commit/9415b09b78a4666f36f479610941605e2a8845ea) but it checks for `/run/user/1000/snap.discord/discord-ipc-<0-9>`. Try and see if https://github.com/Snazzah/SublimeDiscordRP/commit/1ee6d25efccc80a126302612079ebb87a82399c0 fixes this.
